"""Forwarding address generation and IMAP connectivity utilities.

Maps to Section 2.1 (Forwarding Inbox component) and Section 8 (services/).
All functions used by org_service (slug generation), the IMAP worker, and the
PATCH /forwarding/config test endpoint.
"""
from __future__ import annotations

import imaplib
import re
import secrets

import structlog

from app.core.config import settings

log = structlog.get_logger()


def generate_forwarding_slug(org_name: str) -> str:
    """Generate a unique, URL-safe forwarding slug from an organisation name.

    Converts the name to lowercase, replaces whitespace and underscores with
    hyphens, strips non-alphanumeric characters, collapses repeated hyphens,
    and appends a 4-character hex suffix (``secrets.token_hex(2)``) to ensure
    uniqueness across organisations with similar names.

    Example::

        generate_forwarding_slug("ABC Bakery") → "abc-bakery-7f3k"

    Args:
        org_name: Raw organisation name as provided by the user at registration.

    Returns:
        A slug suitable for use as the local-part suffix of a forwarding email
        address (max 55 characters: 50 slugified chars + ``-`` + 4 hex chars).
    """
    slug = org_name.strip().lower()
    # Remove characters that are not word chars, spaces, or hyphens
    slug = re.sub(r"[^\w\s-]", "", slug)
    # Collapse whitespace and underscores into a single hyphen
    slug = re.sub(r"[\s_]+", "-", slug)
    # Collapse consecutive hyphens
    slug = re.sub(r"-+", "-", slug)
    # Trim leading/trailing hyphens
    slug = slug.strip("-")
    # Cap the base slug length so the full slug fits comfortably in a VARCHAR(100)
    slug = slug[:50]

    suffix = secrets.token_hex(2)  # 2 bytes → 4 hex chars (e.g. "7f3k")
    return f"{slug}-{suffix}"


def build_forwarding_address(slug: str) -> str:
    """Build the full forwarding email address for a given slug.

    Format: ``scan+<slug>@<FORWARDING_DOMAIN>``

    Args:
        slug: Organisation forwarding slug generated by
            :func:`generate_forwarding_slug`.

    Returns:
        Fully-qualified forwarding email address, e.g.
        ``scan+abc-bakery-7f3k@phishguard.app``.
    """
    return f"scan+{slug}@{settings.FORWARDING_DOMAIN}"


def test_imap_connection(
    host: str,
    port: int,
    user: str,
    password: str,
) -> bool:
    """Probe an IMAP4-over-SSL connection to verify that credentials are valid.

    Opens an SSL connection to ``host:port`` with a 10-second timeout,
    authenticates with ``user`` / ``password``, and immediately logs out.
    Any exception (connection refused, bad credentials, timeout, TLS error,
    etc.) is caught, logged at WARNING level, and causes ``False`` to be
    returned.

    This function is synchronous — it is intended to be called from a
    Celery task or via ``asyncio.get_event_loop().run_in_executor`` when
    invoked from an async route handler.

    Args:
        host:     IMAP server hostname or IP address.
        port:     IMAP server port (typically 993 for IMAP4 over SSL).
        user:     IMAP login username (typically an email address).
        password: Plain-text IMAP password (callers must decrypt before passing).

    Returns:
        ``True`` if the connection, TLS handshake, and login all succeed;
        ``False`` on any exception.
    """
    try:
        # IMAP4_SSL.timeout parameter is available from Python 3.9+
        imap = imaplib.IMAP4_SSL(host, port, timeout=10)
        imap.login(user, password)
        imap.logout()
        return True
    except Exception as exc:
        log.warning(
            "imap_connection_test_failed",
            host=host,
            port=port,
            user=user,
            error=str(exc),
            exc_type=type(exc).__name__,
        )
        return False
